server:
  tomcat:
    threads:
      max: 1

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      maximum-pool-size: 1
      connection-timeout: 5000

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop